stages:
  - tool
  - build
  - check
  - release

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

include:
  #####################
  # docker image jobs #
  #####################
  - local: '/.gitlab/templates/build-image.yml'
    inputs:
      job-name: image:rust
      image-name: rust
  - local: '/.gitlab/templates/build-image.yml'
    inputs:
      job-name: image:urcu-shared
      job-needs: [image:rust]
      image-name: urcu-shared
  - local: '/.gitlab/templates/build-image.yml'
    inputs:
      job-name: image:urcu-static
      job-needs: [image:rust]
      image-name: urcu-static
  ######################
  # documentation jobs #
  ######################
  - local: '/.gitlab/templates/build-doc.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    inputs:
      job-name: doc:urcu-static
      job-needs: [image:rust]
      deploy-name: rustdoc/merge-request/${CI_MERGE_REQUEST_IID}
      deploy-url: https://gabrielpolloguilbert.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html
  - local: '/.gitlab/templates/build-doc.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    inputs:
      job-name: doc:urcu-static
      job-needs: [image:rust]
      deploy-name: rustdoc/branch/${CI_COMMIT_BRANCH}
      deploy-url: https://gabrielpolloguilbert.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html
  - local: '/.gitlab/templates/build-doc.yml'
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: doc:urcu-static
      job-needs: [image:rust]
      deploy-name: rustdoc/tag/${CI_COMMIT_TAG}
      deploy-url: https://gabrielpolloguilbert.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html

##############
# build jobs #
##############

build:urcu-static:
  needs: [image:urcu-static]
  stage: build
  image: ${CI_REGISTRY_IMAGE}/urcu-static:0.1.0-${CI_COMMIT_SHORT_SHA}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - time cargo build --release --examples --tests --features static
  artifacts:
    paths:
      - target/

build:urcu-shared:
  needs: [image:urcu-shared]
  stage: build
  image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.1.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo build --release --examples --tests
  artifacts:
    paths:
      - target/

##############
# check jobs #
##############

audit:
  needs: [image:rust]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/rust:0.1.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo audit

format:
  needs: [image:rust]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/rust:0.1.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo fmt --check

lint:urcu-static:
  needs: [build:urcu-static]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/urcu-static:0.1.0-${CI_COMMIT_SHORT_SHA}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - time cargo clippy --release --features static

lint:urcu-shared:
  needs: [build:urcu-shared]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.1.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo clippy --release

test:urcu-static:
  needs: [build:urcu-static]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/urcu-static:0.1.0-${CI_COMMIT_SHORT_SHA}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - time cargo nextest run --release --profile=ci --features static
  artifacts:
    paths:
      - target/nextest/ci/junit.xml
    reports:
      junit: target/nextest/ci/junit.xml

test:urcu-shared:
  needs: [build:urcu-shared]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.1.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo nextest run --release --profile=ci
  artifacts:
    paths:
      - target/nextest/ci/junit.xml
    reports:
      junit: target/nextest/ci/junit.xml

################
# release jobs #
################

cargo:
  dependencies: []
  stage: release
  image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.1.0-${CI_COMMIT_SHORT_SHA}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  manual_confirmation: 'Are you sure you want to publish to crates.io?'
  script:
    - ./.gitlab/publish-crates.sh

gitlab:
  dependencies: []
  stage: release
  image: ${CI_REGISTRY_IMAGE}/rust:0.1.0-${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  manual_confirmation: 'Are you sure you want to create a Gitlab release?'
  script:
    - ./.gitlab/release-gitlab.sh
