stages:
  - tool
  - check
  - trigger
  - merge
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

include:
  #####################
  # docker image jobs #
  #####################
  - component: $CI_SERVER_FQDN/gpollo/component-build-image/podman@v0.1.0
    inputs:
      job-name: image:rust
      job-stage: tool
      config-file: .gitlab/image-rust/config.yml
  - component: $CI_SERVER_FQDN/gpollo/component-build-image/podman@v0.1.0
    inputs:
      job-name: image:urcu-shared
      job-stage: tool
      job-needs: [image:rust]
      config-file: .gitlab/image-urcu-shared/config.yml
  - component: $CI_SERVER_FQDN/gpollo/component-build-image/podman@v0.1.0
    inputs:
      job-name: image:urcu-static
      job-stage: tool
      job-needs: [image:rust]
      config-file: .gitlab/image-urcu-static/config.yml
  #################
  # documentation #
  #################
  - local: '/.gitlab/templates/documentation.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    inputs:
      job-name: documentation
      job-needs: [image:rust]
      deploy-name: rustdoc/merge-request/${CI_MERGE_REQUEST_IID}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html
  - local: '/.gitlab/templates/documentation.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    inputs:
      job-name: documentation
      job-needs: [image:rust]
      deploy-name: rustdoc/branch/${CI_COMMIT_BRANCH}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html
  - local: '/.gitlab/templates/documentation.yml'
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: documentation
      job-needs: [image:rust]
      deploy-name: rustdoc/tag/${CI_COMMIT_TAG}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html
  ############
  # coverage #
  ############
  - component: $CI_SERVER_FQDN/gpollo/component-gitlab-downstream/fetch-artifacts@v0.1.0
    inputs:
      job-name: coverage:fetch
      job-needs:
        - job: pipeline:static
          parallel:
            matrix:
              - FLAVOR: flavor-bp
        - job: pipeline:static
          parallel:
            matrix:
              - FLAVOR: flavor-mb
        - job: pipeline:static
          parallel:
            matrix:
              - FLAVOR: flavor-memb
        - job: pipeline:static
          parallel:
            matrix:
              - FLAVOR: flavor-qsbr
        - job: pipeline:shared
          parallel:
            matrix:
              - FLAVOR: flavor-bp
        - job: pipeline:shared
          parallel:
            matrix:
              - FLAVOR: flavor-mb
        - job: pipeline:shared
          parallel:
            matrix:
              - FLAVOR: flavor-memb
        - job: pipeline:shared
          parallel:
            matrix:
              - FLAVOR: flavor-qsbr
      job-stage: merge
      job-artifacts:
        - target/
      config: |
        gitlab-token: $GITLAB_ARTIFACTS_TOKEN
        downstream-pipelines:
          - trigger-job: 'pipeline:static: [flavor-bp]'
            downstream-jobs: [test:coverage]
          - trigger-job: 'pipeline:static: [flavor-mb]'
            downstream-jobs: [test:coverage]
          - trigger-job: 'pipeline:static: [flavor-memb]'
            downstream-jobs: [test:coverage]
          - trigger-job: 'pipeline:static: [flavor-qsbr]'
            downstream-jobs: [test:coverage]
          - trigger-job: 'pipeline:shared: [flavor-bp]'
            downstream-jobs: [test:coverage]
          - trigger-job: 'pipeline:shared: [flavor-mb]'
            downstream-jobs: [test:coverage]
          - trigger-job: 'pipeline:shared: [flavor-memb]'
            downstream-jobs: [test:coverage]
          - trigger-job: 'pipeline:shared: [flavor-qsbr]'
            downstream-jobs: [test:coverage]
  - local: '/.gitlab/templates/coverage.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    inputs:
      job-name: coverage
      job-needs: [coverage:fetch]
      job-stage: merge
      deploy-name: coverage/merge-request/${CI_MERGE_REQUEST_IID}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/llvm-cov/html/index.html
  - local: '/.gitlab/templates/coverage.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    inputs:
      job-name: coverage
      job-needs: [coverage:fetch]
      job-stage: merge
      deploy-name: coverage/branch/${CI_COMMIT_BRANCH}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/llvm-cov/html/index.html
  - local: '/.gitlab/templates/coverage.yml'
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: coverage
      job-needs: [coverage:fetch]
      job-stage: merge
      deploy-name: coverage/tag/${CI_COMMIT_TAG}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/llvm-cov/html/index.html

########################
# downstream pipelines #
########################

pipeline:static:
  needs: [image:urcu-static]
  stage: trigger
  trigger:
    strategy: depend
    include:
      - local: '/.gitlab/templates/downstream.yml'
        inputs:
          pipeline-name: static
          pipeline-image: ${CI_REGISTRY_IMAGE}/urcu-static:0.2.0-${CI_COMMIT_SHORT_SHA}
          cargo-args: --no-default-features --features ${FLAVOR} --features static
  parallel:
    matrix:
      - FLAVOR: [flavor-bp, flavor-mb, flavor-memb, flavor-qsbr]

pipeline:shared:
  needs: [image:urcu-shared]
  stage: trigger
  trigger:
    strategy: depend
    include:
      - local: '/.gitlab/templates/downstream.yml'
        inputs:
          pipeline-name: shared
          pipeline-image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.2.0-${CI_COMMIT_SHORT_SHA}
          cargo-args: --no-default-features --features ${FLAVOR}
  parallel:
    matrix:
      - FLAVOR: [flavor-bp, flavor-mb, flavor-memb, flavor-qsbr]

#######################
# audit & format jobs #
#######################

audit:
  needs: [image:rust]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/rust:0.2.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo audit

format:
  needs: [image:rust]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/rust:0.2.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo fmt --check

################
# release jobs #
################

cargo:
  dependencies: []
  stage: release
  image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.2.0-${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  manual_confirmation: 'Are you sure you want to publish to crates.io?'
  script:
    - ./.gitlab/publish-crates.sh

gitlab:
  dependencies: []
  stage: release
  image: ${CI_REGISTRY_IMAGE}/rust:0.2.0-${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  manual_confirmation: 'Are you sure you want to create a Gitlab release?'
  script:
    - ./.gitlab/release-gitlab.sh
