stages:
  - tool
  - build
  - check
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

include:
  #####################
  # docker image jobs #
  #####################
  - component: $CI_SERVER_FQDN/gpollo/component-build-image/podman@v0.1.0
    inputs:
      job-name: image:rust
      job-stage: tool
      config-file: .gitlab/image-rust/config.yml
  - component: $CI_SERVER_FQDN/gpollo/component-build-image/podman@v0.1.0
    inputs:
      job-name: image:urcu-shared
      job-stage: tool
      job-needs: [image:rust]
      config-file: .gitlab/image-urcu-shared/config.yml
  - component: $CI_SERVER_FQDN/gpollo/component-build-image/podman@v0.1.0
    inputs:
      job-name: image:urcu-static
      job-stage: tool
      job-needs: [image:rust]
      config-file: .gitlab/image-urcu-static/config.yml
  #################
  # documentation #
  #################
  - local: '/.gitlab/templates/documentation.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    inputs:
      job-name: documentation
      job-needs: [image:rust]
      deploy-name: rustdoc/merge-request/${CI_MERGE_REQUEST_IID}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html
  - local: '/.gitlab/templates/documentation.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    inputs:
      job-name: documentation
      job-needs: [image:rust]
      deploy-name: rustdoc/branch/${CI_COMMIT_BRANCH}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html
  - local: '/.gitlab/templates/documentation.yml'
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: documentation
      job-needs: [image:rust]
      deploy-name: rustdoc/tag/${CI_COMMIT_TAG}
      deploy-url: https://gpollo.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/doc/urcu/index.html
  ####################
  # build crate jobs #
  ####################
  - local: '/.gitlab/templates/build-crate.yml'
    inputs:
      job-name: build:urcu-static
      job-needs: [image:urcu-static]
      job-image: ${CI_REGISTRY_IMAGE}/urcu-static:0.2.0-${CI_COMMIT_SHORT_SHA}
      cargo-args: --features static
  - local: '/.gitlab/templates/build-crate.yml'
    inputs:
      job-name: build:urcu-shared
      job-needs: [image:urcu-shared]
      job-image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.2.0-${CI_COMMIT_SHORT_SHA}
  ####################
  # check crate jobs #
  ####################
  - local: '/.gitlab/templates/check-crate.yml'
    inputs:
      job-subname: urcu-static
      job-needs: [build:urcu-static]
      job-image: ${CI_REGISTRY_IMAGE}/urcu-static:0.2.0-${CI_COMMIT_SHORT_SHA}
      cargo-args: --features static
  - local: '/.gitlab/templates/check-crate.yml'
    inputs:
      job-subname: urcu-shared
      job-needs: [build:urcu-shared]
      job-image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.2.0-${CI_COMMIT_SHORT_SHA}

#######################
# audit & format jobs #
#######################

audit:
  needs: [image:rust]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/rust:0.2.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo audit

format:
  needs: [image:rust]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/rust:0.2.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo fmt --check

################
# release jobs #
################

cargo:
  dependencies: []
  stage: release
  image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.2.0-${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  manual_confirmation: 'Are you sure you want to publish to crates.io?'
  script:
    - ./.gitlab/publish-crates.sh

gitlab:
  dependencies: []
  stage: release
  image: ${CI_REGISTRY_IMAGE}/rust:0.2.0-${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  manual_confirmation: 'Are you sure you want to create a Gitlab release?'
  script:
    - ./.gitlab/release-gitlab.sh
