image-name: ${CI_REGISTRY_IMAGE}/urcu-static
image-tag: 0.2.0
credentials:
  - registry: ${CI_REGISTRY}
    username: ${CI_REGISTRY_USER}
    password: ${CI_REGISTRY_PASSWORD}
dependencies:
  - build-argument: BASE_IMAGE
    image-name: ${CI_REGISTRY_IMAGE}/rust
    image-tag: 0.2.0
